### PR TITLE
blkid: cache: add unittests

### PR DESCRIPTION
**Pull request by t-8ch**

### CODE REVIEW

**Comment by karelzak** [comment]
Why do we need to add partition tables to libblkid cache file? The best what we can do for this cache file is to dig a deep grave :-) It's legacy, all data should be in the udev DB, and the cache file should be maintained only for backward compatibility and for high-level libblkid API.

**Comment by t-8ch** [comment]
I was not aware it is deprecated.

I stumbled upon this during some other work and thought it worth fixing.
Want me to drop the changes and only keep the first commit as unittest for the existing code?

**Comment by karelzak** [comment]
> I stumbled upon this during some other work and thought it worth fixing. Want me to drop the changes and only keep the first commit as unittest for the existing code?

yes, please.

**Comment by t-8ch** [comment]
> yes, please.

Done

**Pull request merged**
