### PR TITLE
Stable 2.39/bcachefs fixes

### LINKED ISSUE #2501: Stable release with bcachefs fixes?
v2.39.2 seems to have broken NixOS's setup process https://github.com/NixOS/nixpkgs/pull/252348, We can write work arounds to disable the use of UUID's or [hack around hardcoded mount paths](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/systemd/default.nix#L529-L530) but a release that includes the fixes from master that we can just ship system-wide would be preferable.

### PR DESCRIPTION
**Pull request by t-8ch**
Fixes #2501

### CODE REVIEW

**Comment by YellowOnion** [comment]
@t-8ch thanks so much! will this be a 2.39.3 release?

**Comment by t-8ch** [comment]
@YellowOnion That's for @karelzak to decide and do.
I would guess that it will happen but don't know when.
Also some other fixes should probably go into it.

**Comment by YellowOnion** [comment]
> @YellowOnion That's for @karelzak to decide and do.
> I would guess that it will happen but don't know when.
> Also some other fixes should probably go into it.

I did a `git show` on the three patches and applied it, seems to rebuild fine, just waiting on the entire system to rebuild due to NixOS's pedantic versioning, crypt setup not passing tests tho hmm.

**Comment by t-8ch** [comment]
So encrypted bcachefs support is broken independently of these fixes?
This was not clear to me.

**Comment by YellowOnion** [comment]
@t-8ch doesn't seem related to be bcachefs, it's the `cryptsetup` test suite that fails with the new `util-linux`:

```
CASE: Image in file tests (root capabilities not required)
[1] format
[2] open
Device wipe error, offset 1810432.
Cannot wipe header on device luks-header.
FAILED backtrace:
237 ./compat-test
FAIL: compat-test
```

https://gitlab.com/cryptsetup/cryptsetup/-/blob/v2.6.1/tests/compat-test?ref_type=tags#L237

**Comment by YellowOnion** [comment]
@t-8ch actually this has nothing to do with the patches, a vanilla compile triggers this on my system. I don't know why *shrug*

**Comment by YellowOnion** [comment]
@karelzak all good, I've included the current patch in NixOS for now.

**Comment by phedders** [comment]
Are the patches all in? With bcachefs in 6.7-rc* it would be awesome for all the distros to start getting a new release of blkid in preparation for 6.7 final.

**Comment by karelzak** [comment]
It's merged but not released. We can release v2.39.3; it's unusual to have a .3 release, but why not ... 

There is also some libmount fix; maybe we can add something more to the release. @t-8ch and @masatake, any suggestion for another stable release?

**Comment by t-8ch** [comment]
> any suggestion for another stable release

I guess there are a lot of fixes in master which would make sense to include.
At least the recent stuff for sparc64 and also some older stuff.

**Comment by t-8ch** [comment]
Also fixes for #2528 and #2576 would make sense IMO.

**Comment by YellowOnion** [comment]
bcachefs is now in testing / RC, might be good to try and finalize `.3` soon.

**Comment by karelzak** [comment]
@t-8ch do we need also da91337a8 in stable/v2.39 branch?

**Comment by t-8ch** [comment]
@karelzak It's not strictly a bugfix, but why not.
There are also a bunch of other bugfixes on master that probably should be backported.

**Comment by karelzak** [comment]
> @karelzak It's not strictly a bugfix, but why not. There are also a bunch of other bugfixes on master that probably should be backported.

It sounds like you want to send PR :-)

**Comment by phedders** [comment]
> @t-8ch do we need also [da91337](https://github.com/util-linux/util-linux/commit/da91337a8109beb461c889ffe32701d3cb95aee2) in stable/v2.39 branch?

*Yes* that would be very helpful.

**Pull request merged**
