### PR TITLE
Make the ways of using output stream consistent in usage()

### PR DESCRIPTION
**Pull request by masatake**
I found various combinations were used in usage():

```
puts(...);
fputs(..., stdout);
fpurts(..., out);
printf(...);
fprintf(out, ...);
fprintf(stdout, ...);
```

At least, in one usage() function, they should be consistent.

### CODE REVIEW

**Comment by karelzak** [comment]
Thanks! Consolidation and unification is always a good thing :-)

**Comment by t-8ch** [comment]
It turns out that `puts()` appends a newline which `fputs()` doesn't.

```sh
$ ./wipefs -h
Usage:
 wipefs [options] <device>

Wipe signatures from a device.
Options:
 -a, --all           wipe all magic strings (BE CAREFUL!) -b, --backup        create a signature backup in $HOME -f, --force         force erasure -i, --noheadings    don't print headings -J, --json          use JSON output format -n, --no-act        do everything except the actual write() call -o, --offset <num>  offset to erase, in bytes -O, --output <list> COLUMNS to display (see below) -p, --parsable      print out in parsable instead of printable format -q, --quiet         suppress output messages -t, --types <list>  limit the set of filesystem, RAIDs or partition tables     --lock[=<mode>] use exclusive device lock (yes, no or nonblock)
 -h, --help          display this help
 -V, --version       display version

[..]
```

I can fix it, but I'm not sure what the nicest way would be.
Go back to `puts()`, add an explicit `\n` everywhere or add a new helper?

**Comment by t-8ch** [comment]
@masatake @karelzak Please see my comment above.
In short: `--help` is broken for many commands.

**Comment by masatake** [comment]
I'm sorry for breaking the output.
Putting \n explicitly is better.

**Comment by karelzak** [comment]
Ah.. I missed this during the review. Sorry.

Well, the optimal solution is not to modify output strings, because it means a lot of work for .po files translates. It would be better to revert the puts/fputs changes.

**Pull request merged**
