### PR TITLE
meson: Install binaries to prefix

### PR DESCRIPTION
**Pull request by pothos**
When compiled in Flatpak /usr is read-only and the /app prefix is used.
However, the binary installation did not use the prefix but had /usr
hardcoded.
Use the prefix instead of /usr when assembling the prefix/(s)bin paths.

P.S.: I have one more problem at the moment where within Flatpak libfdisk is not installed (I'm using `-Dauto_features=disabled -Dbuild-libfdisk=enabled -Duse-tty-group=false -Dlibutil=enabled`).

### CODE REVIEW

**Review by brauner — CHANGES_REQUESTED** [review]
Hey, thanks for the patch. Can you please sign-off your commit? :)

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Whoops, I somehow thought this was a patch against @lxc/lxc. Sorry, @karelzak 😅🤷

**Comment by pothos** [comment]
At least `--signoff` is in both contributor guides ;)

**Pull request merged**
