### PR TITLE
libblkid: fix topology chain types mismatch

### PR DESCRIPTION
**Pull request by karelzak**
Reported-by: https://github.com/util-linux/util-linux/pull/2430
References: https://github.com/util-linux/util-linux/commit/3ab9e699a8d90f55e0447516b7e05a8686180467

### CODE REVIEW

**Comment by masatake** [comment]
For running the test, I need the following patch.
https://github.com/util-linux/util-linux/pull/2394/commits/febc0ce95e0d043d89bbbd2d29ac67e45a005015

**Comment by karelzak** [comment]
@masatake I have merged the workflow patch to the master branch. Thanks!

**Comment by masatake** [comment]
Sorry, my patch looks unperfect.

image

**Comment by karelzak** [comment]
> Sorry, my patch looks unperfect.

It's still improving after all the mess I made yesterday ... (sorry again)

**Pull request merged**
