### PR TITLE
libfdisk: add new root and /usr partition types

### PR DESCRIPTION
**Pull request by gyakovlev**
systemd-250 updated Discoverable Partitions Specification with
a lot of new definitions.

1st commit in this PR just adds `root` and `/usr` partition types for new arches.
I'd like to get some feedback and will fill rest of the list if needed:

* root verity
* usr verity
* root verity signature
* usr verity signature

https://github.com/systemd/systemd/commit/6b47cc9897a5d9eac120d24dc62fe0822f324a30
https://systemd.io/DISCOVERABLE_PARTITIONS/

### CODE REVIEW

**Comment by karelzak** [comment]
Thanks for the patch. Go ahead if there are some other types which people (will) use.

What about shorter names, for example: "Linux root (PPC-64 BigEndian)" -> "Linux root (PPC-64 BE)" ?

**Comment by gyakovlev** [comment]
yeah shorter names make sense. I'll adjust. I actually found a list how systemd calls arches internally and yes, they use 2 letter BE/LE.

I'll update PR and will push more partitions from systemd's list later this week.

**Comment by karelzak** [comment]
Hi @gyakovlev, do you have an updated version of the patch? I'd like to add it to the next release :-)

**Comment by gyakovlev** [comment]
sorry lost track of it.
I have something stashed locally, will take a look now

**Comment by gyakovlev** [comment]
pushed shorter names.
so all / and /usr types should be in.

I will fill out the rest (various verity types) too, but imo it's not THAT important as verity is rather niche.

**Comment by gyakovlev** [comment]
I'm not sure if I did not a mistake in the second commit, a lot of copy-paste involved. working on a script that can verify it =)

**Comment by gyakovlev** [comment]
verified, all seems to be correct.
do you want me to squash second commit? or leave it separate?

**Comment by karelzak** [comment]
Thanks, you do not have to reorganize the patches.

I need to talk about verity GUIDs with @mbroz (verity/cryptsetup maintainer), it seems he has some objections.

**Comment by mbroz** [comment]
> I need to talk about verity GUIDs with @mbroz (verity/cryptsetup maintainer), it seems he has some objections.

Not really. The whole concept of GUIDs is broken, you have to maintain labels in paralle instead og checking what is really on the device, but that's not my problem.

**Pull request merged**
