### PR TITLE
meson: fix using options

### PR DESCRIPTION
**Pull request by kekek2**
Sponsored by: Future Crew, LLC

### CODE REVIEW

**Comment by karelzak** [comment]
It looks good to me.  Thomas?

**Review by t-8ch — APPROVED** [review]
Looks good.
It would be nice to be able to convert a `feature` into a `dependency` that can be fed to `executable`.
If that `dependency` becomes a `disabler` when disabled the checking would be much easier.

**Comment by kekek2** [comment]
Please show me an example of how it should be.

**Comment by t-8ch** [comment]
> Please show me an example of how it should be.

This was not a request for you to do something.
Just some wishful thinking about meson.

**Pull request merged**
