### PR TITLE
meson: update version

### PR DESCRIPTION
**Pull request by neheb**
This was not done for the release.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by karelzak** [comment]
Cannot we call tools/git-version-gen script to get the version (like already done in ./configure)?

**Comment by neheb** [comment]
I don’t think so. Would be interesting to try though.

**Comment by eli-schwartz** [comment]
I see no reason this couldn't be done. It's actually relatively common for people to use `version: run_command(..., check: true).stdout().strip()` in the project() function.

**Comment by eli-schwartz** [comment]
#1681

**Pull request closed without merging**
