### PR TITLE
libblkid: apfs: validate checksums

### PR DESCRIPTION
**Pull request by t-8ch**
The apfs superblock contains a checksum based on Fletcher-64. Validate the checksum to make the probing more robust.

### CODE REVIEW

**Comment by karelzak** [comment]
@t-8ch ping? :-)

**Comment by t-8ch** [comment]
Now it seems happier

**Comment by karelzak** [comment]
It seems the build test on arm7 ends with
```
The following packages have unmet dependencies:
   python3-apt : Depends: libapt-pkg6.0t64 (>= 2.8.1) but 2.7.14build2 is to be installed
```
For all PRs :-(

**Comment by karelzak** [comment]
Feedback from Coverity:
```
*** CID 442390:    (INTEGER_OVERFLOW)
/libblkid/src/superblocks/apfs.c: 53 in apfs_fletcher64()
47
48	for (i = 0; i < size / 4; i++) {
49              lo32 += le32_to_cpu(((uint32_t *)buf)[i]);
50              hi32 += lo32;
51      }
52
>>>     CID 442390:    (INTEGER_OVERFLOW)
>>>     Expression "csum_low", which is equal to 18446744073709551615, where "~((lo32 + hi32) % 4294967295UL)" is known to be equal to 4294967295, overflows the type that receives it, an unsigned integer 32 bits
+wide.
53      csum_low = ~((lo32 + hi32) % UINT32_MAX);
54      csum_hi = ~((lo32 + csum_low) % UINT32_MAX);
55
56	return csum_hi << 32 | csum_low;
57     }
58
/libblkid/src/superblocks/apfs.c: 56 in apfs_fletcher64()
50              hi32 += lo32;
51      }
52
53	csum_low = ~((lo32 + hi32) % UINT32_MAX);
54      csum_hi = ~((lo32 + csum_low) % UINT32_MAX);
55
>>>     CID 442390:    (INTEGER_OVERFLOW)
>>>     Expression "csum_hi << 32", which is equal to 18446744069414584320, where "csum_hi" is known to be equal to 18446744073709551615, overflows the type that receives it, an unsigned integer 64 bits wide.
56      return csum_hi << 32 | csum_low;
57     }
58
59     static int apfs_verify_checksum(blkid_probe pr,
60                              const struct apfs_super_block *sb)
61     {
/libblkid/src/superblocks/apfs.c: 56 in apfs_fletcher64()
50              hi32 += lo32;
51      }
52
53      csum_low = ~((lo32 + hi32) % UINT32_MAX);
54      csum_hi = ~((lo32 + csum_low) % UINT32_MAX);
55
>>>     CID 442390:    (INTEGER_OVERFLOW)
>>>     "(csum_hi << 32) | csum_low", which might have underflowed, is returned from the function.
56      return csum_hi << 32 | csum_low;
57     }
58
59     static int apfs_verify_checksum(blkid_probe pr,
60                              const struct apfs_super_block *sb)
61     {

```

**Pull request merged**
