### PR TITLE
build: only build test_enosys if an audit arch exists

### PR DESCRIPTION
**Pull request by t-8ch**
Link: https://lore.kernel.org/util-linux/9211accf8670f28778166a1acdc186e8dd28f2e8.camel@physik.fu-berlin.de/

### CODE REVIEW

**Comment by glaubitz** [comment]
I can confirm that this patch fixes the issue for me.

Tested-by: John Paul Adrian Glaubitz <glaubitz@physik.fu-berlin.de>

**Comment by karelzak** [comment]
Oh.. this is for the stable branch? I have released 2.39.3 without it ...

It would be nice to use any prefix in the pull request name, for example, `stable/v2.39:` to make it more obvious for me.

**Comment by t-8ch** [comment]
Yes, my bad. I forgot it.

**Comment by karelzak** [comment]
I have added https://github.com/util-linux/util-linux/blob/master/.github/labeler.yml, so hopefully we will see a red "STABLE" label for PR against stable/ branches.

**Pull request merged**
