### PR TITLE
lsfd: Fix parsing of /proc/net/udp on kernels without 6c25449e1a32c

### PR DESCRIPTION
**Pull request by t-8ch**

### CODE REVIEW

**Comment by masatake** [comment]
Thank you,

I'm surprised at 6c25449e1a32c594d743df8e8258e8ef870b6a77.
The change implies we will need  to change the "4" to "5" in the future.
This will not be only the issue for udp but also tcp.

Is the following code more defensive? 
```
while (isspace(*sl++));
return (strncmp(sl, "sl", 2) == 0);
```

> It is shorter and avoid out-of-bounds issues.

I agree with "shorter". However, I could not understand "out-of-bounds". For what kind of input, does the "out-of-bounds become an issue?

**Comment by t-8ch** [comment]
> Is the following code more defensive?

Indeed. Your choice :-)



> For what kind of input, does the "out-of-bounds become an issue?

If "line" is very short then `line[3]` will be out of bounds.

**Comment by t-8ch** [comment]
We could also just make tcp use the new udp logic and we should be fine if tcp is changed in the future

**Comment by masatake** [comment]
>>  For what kind of input, does the "out-of-bounds become an issue?

> If "line" is very short then line[3] will be out of bounds.

In that case `line[i] == '\0'` where i < 3 becomes true.. So `line[i] == ' '`, `line[i] == 's'`, or `line[i] == 'l'` is false. Therefore `&& line [i + 1] == ...` is never evaluated.

Am I wrong?

**Comment by t-8ch** [comment]
> Am I wrong?

Welp, indeed this is correct.

**Comment by masatake** [comment]
> Welp, indeed this is correct.

What I wrote is correct, the commit log "It is shorter and *avoid out-of-bounds issues*." may be incorrect. This commit log implies the original code has (potential) out-of-bounds issues.


I would like to take over this pull request.
I will make a new pull request for fixing the issue pointed out by this pull request.

**Comment by t-8ch** [comment]
> What I wrote is correct, the commit log "It is shorter and _avoid out-of-bounds issues_." may be incorrect.

Fully agree.

> I would like to take over this pull request.

Fine by me.

**Pull request closed without merging**
