### PR TITLE
enosys: add support for MIPS, PowerPC and ARC

### PR DESCRIPTION
**Pull request by t-8ch**

### CODE REVIEW

**Comment by t-8ch** [comment]
This should also go to the 2.39 branch

**Comment by mator** [comment]
Thomas, any chance to add sparc64 arch ? 
```
util-linux$ git describe
v2.39-38-g01a0a5560
util-linux$ make
...
make[2]: Entering directory '/home/mator/util-linux'
  CC       misc-utils/enosys-enosys.o
misc-utils/enosys.c:59:6: error: #error Unknown target architecture
   59 | #    error Unknown target architecture
      |      ^~~~~
In file included from ./include/c.h:22,
                 from misc-utils/enosys.c:29:
misc-utils/enosys.c:79:1: error: static assertion failed: "no syscalls found"
   79 | static_assert(sizeof(syscalls) > 0, "no syscalls found");
      | ^~~~~~~~~~~~~
misc-utils/enosys.c: In function ‘main’:
misc-utils/enosys.c:119:39: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
  119 |                         for (i = 0; i < ARRAY_SIZE(syscalls); i++) {
      |                                       ^
misc-utils/enosys.c:130:39: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
  130 |                         for (i = 0; i < ARRAY_SIZE(syscalls); i++)
      |                                       ^
In file included from misc-utils/enosys.c:24:
misc-utils/enosys.c:149:60: error: ‘SECCOMP_ARCH_NATIVE’ undeclared (first use in this function)
  149 |                 [1]  = BPF_JUMP(BPF_JMP | BPF_JEQ | BPF_K, SECCOMP_ARCH_NATIVE, 1, 0),
      |                                                            ^~~~~~~~~~~~~~~~~~~
misc-utils/enosys.c:149:60: note: each undeclared identifier is reported only once for each function it appears in
misc-utils/enosys.c:172:23: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
  172 |         for (i = 0; i < ARRAY_SIZE(syscalls); i++) {
      |                       ^
make[2]: *** [Makefile:12038: misc-utils/enosys-enosys.o] Error 1
make[2]: Leaving directory '/home/mator/util-linux'
make[1]: *** [Makefile:15770: all-recursive] Error 1
make[1]: Leaving directory '/home/mator/util-linux'
make: *** [Makefile:6716: all] Error 2
```

**Comment by karelzak** [comment]
> Can we move `enosys` arch check support to `configure`?

Yes, it would be nice ;-)

**Comment by t-8ch** [comment]
It is a bad solution indeed.

I have two approaches that I think are nicer:

* #warn during build and disable arch validation. This way users don't have to care and still know something is not great and can report it.
* Split the preprocessor checking into its own header file and try to load that during configure to check if enosys can be built.

**Pull request merged**
