### PR TITLE
po-man: fix incorrect command name translations

### PR DESCRIPTION
**Pull request by t-8ch**
This should also be applied to 2.39

### CODE REVIEW

**Comment by yurchor** [comment]
Thanks for fixing this. Sorry for my mistakes.

**Comment by karelzak** [comment]
We need to fix this on TP.

**Comment by t-8ch** [comment]
I sent a mail to the affected TP teams.
I'm not sure how TP interacts with patch releases.
Currently these manpages are generated with the wrong filename.

**Comment by yurchor** [comment]
> We need to fix this on TP.

Fixed on TP for Ukrainian.

**Comment by mariobl** [comment]
Fixed on TP for French.

**Comment by t-8ch** [comment]
Fixed in import from TP

**Pull request closed without merging**
