### PR TITLE
cal: fix week number colors and improve vertical output

### PR DESCRIPTION
**Pull request by karelzak**
* Do not use reverse as the default color.
* Always print the colorized week number when the "weeknumber" color sequence is available.
* Save the color sequence to reduce the number of cal_get_color_* calls.

Addreses: https://bugzilla.redhat.com/show_bug.cgi?id=2280687

### CODE REVIEW

**Comment by t-8ch** [comment]
Any chance for a test?

**Comment by karelzak** [comment]
There are tests for all functionality with default settings; the problem is that the tests do not define any color schema (terminal-colors.d/cal.schema).

**Comment by karelzak** [comment]
I'll do it :-)

**Comment by t-8ch** [comment]
I thought about adding a new testcase that specifically only tests the colors.

**Comment by karelzak** [comment]
There are tests/ts/cal/color and tests/ts/cal/color; I have added tests/ts/cal/terminal-colors.d/cal.scheme for these tests.

**Pull request merged**
