### PR TITLE
dmesg timestamps

### PR DESCRIPTION
**Pull request by karelzak**

### CODE REVIEW

**Comment by rishabh-thukral** [comment]
@karelzak 
Would we need to rebase the PR before merging?

**Comment by t-8ch** [comment]
Some testcases would be great

**Comment by rishabh-thukral** [comment]
# DMESG Timestamp Testing
---
I pulled this branch, compiled and built it locally. I executed the subsequnt commands to test the functionality.

```
$./dmesg --version
dmesg from util-linux 2.39.1026-423ed
```

## Updated `--time-format` option
```
$./dmesg | tail | head -1
[17159596.699613] device vethab20cf5 entered promiscuous mode
$./dmesg --time-format raw | tail | head -1
[17159596.699613] device vethab20cf5 entered promiscuous mode
$./dmesg --time-format raw --time-format ctime | tail | head -1
[17159596.699613] [Fri Dec 22 12:26:24 2023] device vethab20cf5 entered promiscuous mode
$./dmesg --time-format raw --time-format ctime --time-format reltime | tail | head -1
[17159596.699613] [Fri Dec 22 12:26:24 2023] [  +0.000000] device vethab20cf5 entered promiscuous mode
$./dmesg --time-format raw --time-format ctime --time-format reltime --time-format iso | tail | head -1
[17159596.699613] [Fri Dec 22 12:26:24 2023] [  +0.000000] 2023-12-22T12:26:24,559615-08:00 device vethab20cf5 entered promiscuous mode
$./dmesg --time-format raw --time-format ctime --time-format reltime --time-format iso --time-format delta | tail | head -1
[17159596.699613 <    0.000000>] [Fri Dec 22 12:26:24 2023] [  +0.000000] 2023-12-22T12:26:24,559613-08:00 device vethab20cf5 entered promiscuous mode
$./dmesg --time-format iso --time-format reltime --time-format ctime --time-format delta | tail | head -1
2023-12-22T12:26:24,559613-08:00 [  +0.000000] [Fri Dec 22 12:26:24 2023 <    0.000000>] device vethab20cf5 entered promiscuous mode
$./dmesg --time-format ctime --time-format reltime --time-format iso --time-format delta | tail | head -1
[Fri Dec 22 12:26:24 2023 <    0.000000>] [  +0.000000] 2023-12-22T12:26:24,559613-08:00 device vethab20cf5 entered promiscuous mode
```

## Interaction with `-d`/`--delta` option
```
$./dmesg -d  | tail | head -1
[17159596.699613 <    0.000000>] device vethab20cf5 entered promiscuous mode
$./dmesg -d --time-format raw | tail | head -1
[17159596.699613 <    0.000000>] device vethab20cf5 entered promiscuous mode
$./dmesg -d --time-format iso | tail | head -1
2023-12-22T12:26:24,559613-08:00 [<    0.000000>] device vethab20cf5 entered promiscuous mode
$./dmesg -d --time-format reltime --time-format iso | tail | head -1
[  +0.000000] 2023-12-22T12:26:24,559613-08:00 [<    0.000000>] device vethab20cf5 entered promiscuous mode
$./dmesg -d --time-format ctime --time-format reltime --time-format iso | tail | head -1
[Fri Dec 22 12:26:24 2023 <    0.000000>] [  +0.000000] 2023-12-22T12:26:24,559615-08:00 device vethab20cf5 entered promiscuous mode
$./dmesg -d --time-format raw --time-format ctime --time-format reltime --time-format iso | tail | head -1
[17159596.699613 <    0.000000>] [Fri Dec 22 12:26:24 2023] [  +0.000000] 2023-12-22T12:26:24,559615-08:00 device vethab20cf5 entered promiscuous mode
```

## Interaction with `-e`/`--reltime` and `-T`/`--ctime` option
```
$./dmesg -de  | tail | head -1
[  +0.000000] [<    0.000000>] device vethab20cf5 entered promiscuous mode
$./dmesg -ed  | tail | head -1
[  +0.000000] [<    0.000000>] device vethab20cf5 entered promiscuous mode
$./dmesg -Tde  | tail | head -1
[Fri Dec 22 12:26:24 2023 <    0.000000>] [  +0.000000] device vethab20cf5 entered promiscuous mode
$./dmesg -deT | tail | head -1
[  +0.000000] [Fri Dec 22 12:26:24 2023 <    0.000000>] device vethab20cf5 entered promiscuous mode
$./dmesg -de --time-format ctime | tail | head -1
[  +0.000000] [Fri Dec 22 12:26:24 2023 <    0.000000>] device vethab20cf5 entered promiscuous mode
$./dmesg -e --time-format raw --time-format ctime --time-format iso | tail | head -1
[  +0.000000] [17159596.699613] [Fri Dec 22 12:26:24 2023] 2023-12-22T12:26:24,559613-08:00 device vethab20cf5 entered promiscuous mode
$./dmesg -H --time-format raw --time-format ctime --time-format iso | tail | head -1
[  +0.000000] [17159596.699613] [Fri Dec 22 12:26:24 2023] 2023-12-22T12:26:24,559615-08:00 device vethab20cf5 entered promiscuous mode
$./dmesg --time-format ctime --time-format iso | tail | head -1
[Fri Dec 22 12:26:24 2023] 2023-12-22T12:26:24,559613-08:00 device vethab20cf5 entered promiscuous mode
$./dmesg -T --time-format iso | tail | head -1
[Fri Dec 22 12:26:24 2023] 2023-12-22T12:26:24,559612-08:00 device vethab20cf5 entered promiscuous mode
```

## Interaction with `-t`/`--notime` option
```
$./dmesg --time-format raw --time-format ctime --time-format iso | tail | head -1
[17159596.699613] [Fri Dec 22 12:26:24 2023] 2023-12-22T12:26:24,559613-08:00 device vethab20cf5 entered promiscuous mode
$./dmesg -t --time-format raw --time-format ctime --time-format iso | tail | head -1
device vethab20cf5 entered promiscuous mode
$./dmesg --time-format raw --time-format ctime -t --time-format iso | tail | head -1
device vethab20cf5 entered promiscuous mode
$./dmesg --time-format raw --time-format ctime --time-format iso -t | tail | head -1
device vethab20cf5 entered promiscuous mode
$./dmesg --time-format raw --time-format ctime --time-format iso --time-format notime | tail | head -1
device vethab20cf5 entered promiscuous mode
```

## Interaction with `-r`/`--raw` option
```
$./dmesg -r | tail | head -1
<6>[17159596.699613] device vethab20cf5 entered promiscuous mode
$./dmesg -r --time-format ctime | tail | head -1
<6>[17159596.699613] device vethab20cf5 entered promiscuous mode
$./dmesg -r --time-format ctime --time-format delta | tail | head -1
<6>[17159596.699613] device vethab20cf5 entered promiscuous mode
$./dmesg -r --time-format ctime --time-format iso --time-format delta | tail | head -1
<6>[17159596.699613] device vethab20cf5 entered promiscuous mode
$./dmesg -r --time-format ctime --time-format iso --time-format reltime --time-format delta | tail | head -1
<6>[17159596.699613] device vethab20cf5 entered promiscuous mode
$./dmesg -r --time-format ctime --time-format iso --time-format reltime --time-format delta --time-format raw | tail | head -1
<6>[17159596.699613] device vethab20cf5 entered promiscuous mode
```

## Interaction with `-x`/`--decode` option
```
$./dmesg -x | tail | head -1
kern  :info  : [17159596.699613] device vethab20cf5 entered promiscuous mode
$./dmesg -x --time-format ctime | tail | head -1
kern  :info  : [Fri Dec 22 12:26:24 2023] device vethab20cf5 entered promiscuous mode
$./dmesg -x --time-format ctime --time-format delta | tail | head -1
kern  :info  : [Fri Dec 22 12:26:24 2023 <    0.000000>] device vethab20cf5 entered promiscuous mode
$./dmesg -x --time-format ctime --time-format iso --time-format delta | tail | head -1
kern  :info  : [Fri Dec 22 12:26:24 2023 <    0.000000>] 2023-12-22T12:26:24,559612-08:00 device vethab20cf5 entered promiscuous mode
$./dmesg -x --time-format ctime --time-format iso --time-format reltime --time-format delta | tail | head -1
kern  :info  : [Fri Dec 22 12:26:24 2023 <    0.000000>] 2023-12-22T12:26:24,559613-08:00 [  +0.000000] device vethab20cf5 entered promiscuous mode
$./dmesg -x --time-format ctime --time-format iso --time-format reltime --time-format delta --time-format raw | tail | head -1
kern  :info  : [Fri Dec 22 12:26:24 2023] 2023-12-22T12:26:24,559613-08:00 [  +0.000000] [17159596.699613 <    0.000000>] device vethab20cf5 entered promiscuous mode
```

## Updated help command
```
$./dmesg -h | grep -C 2 "raw]"
 -t, --notime                don't show any timestamp with messages
     --time-format <format>  show timestamp using the given format:
                               [delta|reltime|ctime|notime|iso|raw]
Suspending/resume will make ctime and iso timestamps inaccurate.
     --since <time>          display the lines since the specified time
```
The list of commands used in the testing above is attached: [CommandsList.md](https://github.com/util-linux/util-linux/files/13756704/Upstream_Testing_MultipleFormat_CMDS.md)

**Comment by t-8ch** [comment]
I meant automatic tests in `tests/ts/dmesg/` :-)

**Comment by rishabh-thukral** [comment]
Hi @t-8ch ,
I've created a separate PR on top of this branch to include an automatic test to verify the functionality of supporting multiple timestamp formats. 
[Here is a link to the PR](https://github.com/karelzak/util-linux-work/pull/2), please feel free to add comments on including/excluding test cases.

**Comment by karelzak** [comment]
https://github.com/karelzak/util-linux-work/pull/2 merged.

**Comment by rishabh-thukral** [comment]
@karelzak @t-8ch 
Do you recommend rebasing the PR branch with the current master?

**Comment by t-8ch** [comment]
@rishabh-thukral The branch can be merged cleanly, so it should not be necessary.
Wouldn't hurt either, though.

**Comment by rishabh-thukral** [comment]
@t-8ch  I don't have write/merge access to this branch.

**Pull request merged**
