### PR TITLE
wdctl: read firmware_version from sysfs

### PR DESCRIPTION
**Pull request by t-8ch**
Note: This is pending kernel support in https://lore.kernel.org/lkml/20221125222315.4925-1-linux@weissschuh.net/

### CODE REVIEW

**Comment by karelzak** [comment]
Good idea.

**Comment by karelzak** [comment]
What is the current status of the kernel code?

**Comment by t-8ch** [comment]
No progress either way yet on kernel side.

**Comment by t-8ch** [comment]
This has been merged into the watchdog tree.

The watchdog PR for the 6.3 mergewindow has not been submitted, but I *suspect* it should make it into 6.3.

**Comment by t-8ch** [comment]
The kernel part has now be merged into Linus' tree

**Pull request merged**
