### PR TITLE
 all_errnos/all_syscalls: don't hardcode AWK invocation 

### PR DESCRIPTION
**Pull request by t-8ch**
See the commit message, https://lore.kernel.org/util-linux/31ccace2e5912ffc428e065cd66764088c625c4d.camel@physik.fu-berlin.de/ and #2949 (which this PR replaces)

### CODE REVIEW

**Comment by karelzak** [comment]
Thanks! It would also be usable for a stable branch, too, right?

**Comment by t-8ch** [comment]
> It would also be usable for a stable branch, too, right?

Yes, but it will need another fix for Debians default awk implementation.

**Comment by karelzak** [comment]
Yes, I've seen the issue with AWK (sad story ..., I like awk :-)

**Comment by karelzak** [comment]
Please prepare a PR for the stable branch if all will be ready :-)

**Pull request merged**
