### PR TITLE
uuidparse: only report type/version for DCE variant

### PR DESCRIPTION
**Pull request by t-8ch**
The type/version is only defined in scope for the DCE variant.

From RFC4122 Section 4.1.1:

"the interpretation of all other bits in the UUID depends on the setting of the bits in the variant field."

### CODE REVIEW

**Comment by karelzak** [comment]
hmm... I do not interpret it as only the "DCE variant" has type ;-) I read it as "there is a dependence on variant".  It seems that the TYPE is valid for other variants, too.

**Comment by t-8ch** [comment]
TYPE in general yes, but not the types currently recognized by uuidparse/libuuid

**Comment by t-8ch** [comment]
Other variants don't necessarily determine their versions through the same bits.

**Comment by karelzak** [comment]
I see; we also in code use UUID_TYPE_DCE_* for the types. 

It would be nice to gather types for the other variants to make uuidparse more generic.

**Comment by t-8ch** [comment]
I'm not sure if the other variants are really used at all.

(And if they are to be added IMO this should be a dedicated PR)

**Pull request merged**
