### PR TITLE
login: preserve locale related environment variables

### PR DESCRIPTION
**Pull request by rpigott**
If it has already been set, let's preserve the locale for the benefit of the login session. Login shells will already set the locale variables as needed, so this is for the benefit of non-shell programs that have been configured as the user's "login shell".

### CODE REVIEW

**Comment by rpigott** [comment]
This implements the intent of systemd/systemd#6023. See also systemd/systemd#33996.

**Comment by karelzak** [comment]
I have nothing against protecting some variables, but it should be implemented in a backward-compatible way. Now, the default is to reset environ[] and remove all locale-related variables.

Maybe we can implement it generously and use `/etc/login.defs` to define which variables should be protected. The same functionality is provided for su(1) by --whitelist-environment=. It seems better than hardcoding any list of variables in login(1).

**Comment by karelzak** [comment]
I can implement it.

**Comment by rpigott** [comment]
That sounds like a good solution to me.

**Comment by karelzak** [comment]
Closing in favor of https://github.com/util-linux/util-linux/pull/3184

**Pull request closed without merging**
