### PR TITLE
ci: run full testsuite under musl libc

### PR DESCRIPTION
**Pull request by t-8ch**

### CODE REVIEW

**Comment by t-8ch** [comment]
Alpine (using musl libc) seems to have quite some issues with our testsuite:
https://git.alpinelinux.org/aports/tree/main/util-linux/APKBUILD#n107

`lscpu/lscpu` and  `hardlink/options` should be already fixed in master.
`dmesg/limit` and `lib/timeutils` are fixed by this PR.

`col/multibyte` is also blocking this PR, some input would be great :-)

**Comment by t-8ch** [comment]
CC @ncopa who is the maintainer for util-linux in Alpine.

**Comment by t-8ch** [comment]
So `col` is not really compatible with musl.
`col` does `getwchar()` and if that fails with EILSEQ it tries to read the same character again with `getchar()`.
On musl however `getwchar` will have consumed the character that lead to the error and `getchar()` will actually read the next character.

**Comment by karelzak** [comment]
> So `col` is not really compatible with musl. `col` does `getwchar()` and if that fails with EILSEQ it tries to read the same character again with `getchar()`. On musl however `getwchar` will have consumed the character that lead to the error and `getchar()` will actually read the next character.

Frankly, I'd assume this behavior is everywhere, when you read anything then it's done ;-)

Maybe use the same solution we have in the column.c, use normal read-based way and then convert to wide-char.

**Comment by t-8ch** [comment]
Is it worth doing larger refactoring on `col`? It seems to be deprecated :-)

**Comment by karelzak** [comment]
Maybe it is a waste of time and ignore it if getwchar is not available or does not work as expected is a better solution ...

**Comment by t-8ch** [comment]
Deciding if it works would require code execution during configure which doesn't  work for cross-compilation.

How about just testing for glihc header defines?
If somebody complains we can revise it.

**Comment by t-8ch** [comment]
This should be ready

**Pull request merged**
